deployment:
  type: "server"
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  containerPort: 3000
  sleepOnPreStopEnabled: false
application:
  entryPoint:
    - tail
    - -f
    - /dev/null
secret:
  name: testing-secret
image:
  path: alipine
  tag: latest
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 4000m
    memory: 16Gi
  requests:
    cpu: 100m
    memory: 128Mi
service:
  type: ClusterIP
  port: 80
  targetPort: http
  portName: http
  annotations: {}