apiVersion: v1
kind: Deployment
metadata:
  name: helm-testing
  namespace: default
  labels:
    app: helm-testing
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: helm-testing
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable}}
      maxSurge : {{ .Values.deployment.strategy.rollingUpdate.maxSurge}}
    type: RollingUpdate
    spec:
      containers:
      - args:
          {{- range .Values.application.entryPoint }}
          - {{ . }}
          {{- end }}
        envFrom:
        - secretRef:
            name: {{ .Values.secret.name }}
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        image: "{{ .Values.image.path }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
  template:
    metadata:
      labels:
        app: helm-testing